### ISSUE TITLE
Origin/meaning of "WMR"?

### ISSUE THREAD

**Issue by briantully** [preactjs/wmr#228]
Is it an acronym? I didn't see anything in the README referencing the origin or meaning of "WMR", so was hoping someone could shed some light.

**Comment by EmilTholin** [comment]
I haven't heard anything definitive, but I did see [this interaction on Twitter](https://twitter.com/_developit/status/1334325584319614976). 🕵️

**Comment by developit** [comment]
Heh - yeah WMR was originally a bad pun: "Warm Module Replacement". It's a reference to Hot Module Replacement, since WMR started out as an experiment to see if HMR could be brought directly to native ES Modules. 

Since then though, we've been pretending WMR means "Web Modules Runtime". It works well because the "big idea" with WMR is about doing things on the fly ("at runtime").

**Comment by papandreou** [comment]
I instinctively read the abbreviation as “Weapon of Mass Reduction” 😸
