### ISSUE TITLE
packages/wmr/demo demonstrates module.hot usage, but isn't prefresh activated by default?

### ISSUE THREAD

**Issue by danielweck** [preactjs/wmr#402]
Should this line be removed?

https://github.com/preactjs/wmr/blob/fe51b7eb3a65740571863fbeebf3367b74a9ddfe/packages/wmr/demo/public/index.tsx#L55-L56

Note that I posted a related PR comment here (`packages/ssr-plugin/example`):

https://github.com/preactjs/wmr/pull/400/files#r589005348

**Comment by JoviDeCroock** [comment]
This is needed because currently we aren't using [`@prefresh/babel`](https://github.com/JoviDeCroock/prefresh/tree/main/packages/babel) this means that we aren't registering components without them getting explicitly exported.

We are looking to port this to [`acorn-traverse`](https://github.com/preactjs/wmr/blob/main/packages/wmr/src/lib/acorn-traverse.js) or [`swc`](https://swc.rs/), so for the time being this is correct as we are not exporting `<App />` so this runtime can't pick up on it.

If you want to read more on how Prefresh works, I wrote a small post https://dev.to/jovidecroock/prefresh-fast-refresh-for-preact-26kg

**Comment by danielweck** [comment]
Thank you very much for your very informative explanation, much appreciated!

**Comment by danielweck** [comment]
> this is correct as we are not exporting `<App />`

Presumably, you don't mean that:

https://github.com/preactjs/wmr/blob/fe51b7eb3a65740571863fbeebf3367b74a9ddfe/packages/wmr/demo/public/index.tsx#L24

...do you?

**Comment by JoviDeCroock** [comment]
Well, it's not an import path, we don't know how this fits into the module-graph. i.e. This is implicitly imported in `index.html` so the parent connector isn't an obvious tool in the chain.

**Comment by danielweck** [comment]
Got it, thanks.

**Comment by danielweck** [comment]
Should the `create-wmr` template be updated to reflect this?

https://github.com/preactjs/wmr/blob/main/packages/create-wmr/tpl/public/index.js
