### ISSUE TITLE
Error when importing same file twice in the same module

### ISSUE THREAD

**Issue by marvinhagemeister** [preactjs/wmr#730]
Reported via Slack:

> after migrating to 3.3.1 i noticed interesting issue that in development if i import one same file twice, it will not properly include the file second time (not sure if its related to alias). Just throwing it here as an observation, i’ll provide more details later maybe. No biggie
>
> Yeah, so if I have something like `import {a, b} from 'aliased/file.js'` and then split it into `import {a} from 'aliased/file.js'; import {b} from 'aliased/file.js;'` the second time file will be served as html. In HMR I get Failed to fetch dynamically imported module:
I couldn’t reproduce it with importing from npm, i think it may be related to aliasing.

**Comment by developit** [comment]
It's interesting that the second import ends up being served HTML. That leads me to think there's something going on with repeated import sources themselves:

```js
import { a } from './foo.js';
import { b } from './foo.js';
```

One thing I noticed as I re-read through the sourcemap changes from #715 was that it seems like it may be invoking resolve() multiple times for the same specifier now, since the `toResolve` Array is per-callsite, vs per-specifier. I'm not 100% sure how that could end up skipping things, but it might fail to resolve a second time?

**Comment by marvinhagemeister** [comment]
I'm having trouble reproducing the error. Tried with 50 imports and a random delay in a plugin that resolves that file :S

**Comment by Inviz** [comment]
Thanks for trying, I'll try to provide a reduced case later this week.

**Comment by marvinhagemeister** [comment]
Just checked again and I'm not able to reproduce it. Let's close this for now. We can always re-open it in case it pops up again 👍
